# Generated by Django 5.1.6 on 2025-06-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelerprofile',
            name='favorite_destinations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='travelerprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='travelerprofile',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('pt', 'Portuguese')], default='en', max_length=10),
        ),
    ]
