# Generated by Django 5.1.6 on 2025-02-17 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0003_itinerary_generated_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='lng',
        ),
        migrations.AddField(
            model_name='itinerary',
            name='extras',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='food_preference',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='interest_places',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='transport_mode',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='travelers',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
