# Generated by Django 5.1.6 on 2025-02-17 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0005_rename_transport_mode_itinerary_transport_modes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itinerary',
            old_name='food_preference',
            new_name='food_preferences',
        ),
    ]
