# Generated by Django 5.1.6 on 2025-03-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0010_remove_trip_user_remove_review_trip_itinerary_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='trip_type',
            field=models.CharField(blank=True, default='turismo', max_length=50, null=True),
        ),
    ]
