# Generated by Django 5.1.6 on 2025-04-14 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0011_itinerary_trip_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary',
            name='food_preferences',
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='interest_places',
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='transport_mode',
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='trip_type',
        ),
    ]
