# Generated by Django 5.1.6 on 2025-04-17 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0012_remove_itinerary_food_preferences_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='extras',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='travelers',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
