# Generated by Django 5.1.6 on 2025-05-19 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0013_alter_itinerary_extras_alter_itinerary_travelers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary',
            name='lng',
        ),
    ]
