# Generated by Django 5.1.6 on 2025-05-19 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0014_remove_itinerary_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
