# Generated by Django 5.1.6 on 2025-02-17 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0006_rename_food_preference_itinerary_food_preferences'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itinerary',
            old_name='transport_modes',
            new_name='transport_mode',
        ),
    ]
