name: frontend
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  flutter_secure_storage: ^9.0.0
  provider: ^6.0.0
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.0
  smooth_page_indicator: ^1.1.0
  flutter_staggered_animations: ^1.1.1
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  intl: ^0.19.0
  flutter_markdown: ^0.7.4+1
  url_launcher: ^6.3.1
  firebase_core: ^3.13.1
  cloud_firestore: ^5.6.8
  firebase_auth: ^5.5.4
  firebase_storage: ^12.4.6
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true


