// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpQTJ3M5k_C4B9RFxZJ7T8dKJhP2Y5KzU',
    appId: '1:448618578101:web:8f3e2a4b1c7d9e5f6a8b9c',
    messagingSenderId: '448618578101',
    projectId: 'plantrip-b26fd',
    authDomain: 'plantrip-b26fd.firebaseapp.com',
    storageBucket: 'plantrip-b26fd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBWxZrOQ2CUNqLu0nB3Nh7US1bF2kRXvk',
    appId: '1:1044383439233:android:10680235989cf97cf0b080',
    messagingSenderId: '1044383439233',
    projectId: 'plantrip-b26fd',
    storageBucket: 'plantrip-b26fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpQTJ3M5k_C4B9RFxZJ7T8dKJhP2Y5KzU',
    appId: '1:448618578101:ios:8f3e2a4b1c7d9e5f6a8b9c',
    messagingSenderId: '448618578101',
    projectId: 'plantrip-b26fd',
    storageBucket: 'plantrip-b26fd.appspot.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpQTJ3M5k_C4B9RFxZJ7T8dKJhP2Y5KzU',
    appId: '1:448618578101:ios:8f3e2a4b1c7d9e5f6a8b9c',
    messagingSenderId: '448618578101',
    projectId: 'plantrip-b26fd',
    storageBucket: 'plantrip-b26fd.appspot.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpQTJ3M5k_C4B9RFxZJ7T8dKJhP2Y5KzU',
    appId: '1:448618578101:web:8f3e2a4b1c7d9e5f6a8b9c',
    messagingSenderId: '448618578101',
    projectId: 'plantrip-b26fd',
    authDomain: 'plantrip-b26fd.firebaseapp.com',
    storageBucket: 'plantrip-b26fd.appspot.com',
  );
}